export const ROUTES = {
  home: '/',
  login: '/login',
  register: '/register',
  workspaces: '/workspaces',
  workspaceNew: '/workspaces/new',
  workspaceDashboard: (wsId: string) => `/w/${wsId}`,
  workspaceProfile: (wsId: string) => `/w/${wsId}/profile`,
  workspaceSearch: (wsId: string) => `/w/${wsId}/search`,
  workspaceItems: (wsId: string) => `/w/${wsId}/items`,
  workspaceContainers: (wsId: string) => `/w/${wsId}/containers`,
  workspaceLocations: (wsId: string) => `/w/${wsId}/locations`,
  workspaceSites: (wsId: string) => `/w/${wsId}/sites`,
  workspaceSiteDetail: (wsId: string, siteId: string) => `/w/${wsId}/sites/${siteId}`,
  workspaceSiteExplorer: (wsId: string, siteId: string) => `/w/${wsId}/sites/${siteId}/explorer`,
  workspaceMemberDetail: (wsId: string, memberId: string) => `/w/${wsId}/members/${memberId}`,
  workspaceContainerDetail: (wsId: string, containerId: string) => `/w/${wsId}/containers/${containerId}`,
  workspaceMembers: (wsId: string) => `/w/${wsId}/members`,
  workspaceActivity: (wsId: string) => `/w/${wsId}/activity`,
  workspaceSettings: (wsId: string) => `/w/${wsId}/settings`,
  workspaceItemDetail: (wsId: string, itemId: string) => `/w/${wsId}/items/${itemId}`,
  notFound: '*',
} as const;
