export const ROUTES = {
  home: '/',
  login: '/login',
  register: '/register',
  invitationsInbox: '/invitations',
  invitationAccept: (token: string) => `/invitations/${encodeURIComponent(token)}`,
  settings: '/settings',
  workspaces: '/workspaces',
  workspaceNew: '/workspaces/new',
  workspaceDashboard: (wsId: string) => `/w/${wsId}`,
  workspaceProfile: (wsId: string) => `/w/${wsId}/profile`,
  workspaceSearch: (wsId: string) => `/w/${wsId}/search`,
  workspaceActivity: (wsId: string) => `/w/${wsId}/activity`,
  workspaceReports: (wsId: string) => `/w/${wsId}/reports`,
  workspaceNotifications: (wsId: string) => `/w/${wsId}/notifications`,
  workspaceItems: (wsId: string) => `/w/${wsId}/items`,
  workspaceAssets: (wsId: string) => `/w/${wsId}/assets`,
  workspaceAssetDetail: (wsId: string, assetId: string) => `/w/${wsId}/assets/${encodeURIComponent(assetId)}`,
  workspaceStock: (wsId: string) => `/w/${wsId}/stock`,
  workspaceStockDetail: (wsId: string, stockEntryId: string) => `/w/${wsId}/stock/${encodeURIComponent(stockEntryId)}`,
  workspaceContainers: (wsId: string) => `/w/${wsId}/containers`,
  workspaceBorrowOrders: (wsId: string) => `/w/${wsId}/borrow-orders`,
  workspaceBorrowOrderDetail: (wsId: string, orderId: string) => `/w/${wsId}/borrow-orders/${encodeURIComponent(orderId)}`,
  workspaceMasterData: (wsId: string) => `/w/${wsId}/master-data`,
  workspaceMemberDetail: (wsId: string, memberId: string) => `/w/${wsId}/members/${memberId}`,
  workspaceContainerDetail: (wsId: string, containerId: string) => `/w/${wsId}/containers/${containerId}`,
  workspaceMembers: (wsId: string) => `/w/${wsId}/members`,
  workspaceSettings: (wsId: string) => `/w/${wsId}/settings`,
  workspaceItemDetail: (wsId: string, itemId: string) => `/w/${wsId}/items/${encodeURIComponent(itemId)}`,
  notFound: '*',
} as const;
